all:
  vars:
    # The generated inventory is assumed to be used from the clab host.
    # Hence no http proxy should be used. Therefore we make sure the http
    # module does not attempt using any global http proxy.
    ansible_httpapi_use_proxy: false
  children:
    cisco_iol:
      vars:
        # ansible_connection: set ansible_connection variable if required
        ansible_user: admin
        ansible_password: admin
      hosts:
        branch1:
          ansible_host: 198.51.100.21
        branch2:
          ansible_host: 198.51.100.31
        core1:
          ansible_host: 198.51.100.11
        dc1:
          ansible_host: 198.51.100.12
    linux:
      hosts:
        client1:
          ansible_host: 198.51.100.22
        client2:
          ansible_host: 198.51.100.32
        grafana:
          ansible_host: 198.51.100.50
        influxdb-v2:
          ansible_host: 198.51.100.51
        telegraf:
          ansible_host: 198.51.100.8